use_frameworks!

target 'GenericTrackingFramework_Example' do
  pod 'GenericTrackingFramework', :path => '../'

  target 'GenericTrackingFramework_Tests' do
    inherit! :search_paths

    
  end
end
